### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by peat-psuwit**
This PR builds upon @NotKit's work on building on GitHub Actions (on `dynparts` branch) to add the "release" part to it. When this PR is merged, the "continuous" tag/release will contain the built initrd once again. This allows us to build the Android image which is "compatible" with Focal.

Note that this differs from `dynparts` version, in that the release action only runs on the `halium` branch, and to the `continuous` tag directly.

For this PR in action, see Actions in my fork: https://github.com/peat-psuwit/initramfs-tools-halium/actions

### CODE REVIEW

**Review by NotKit — APPROVED** [review]
Looks good to me

**Comment by peat-psuwit** [comment]
@NotKit I cannot merge this, not a member. Could you please merge?

**Comment by NotKit** [comment]
@peat-psuwit I don't have access to the master branch of this repository either. Maybe @UniversalSuperBox does?

**Comment by UniversalSuperBox** [comment]
I can merge this, but I think I'd rather wait until Monday to do so. Just in case.

**Comment by NotKit** [comment]
What does that change besides the date in the calendar?

**Comment by UniversalSuperBox** [comment]
If it doesn't work and all the halium ports fail to boot tomorrow, I don't have to interrupt my weekend to fix it.

**Comment by NotKit** [comment]
Weekends? That's a luxury. Ok, makes sense then.

**Comment by UniversalSuperBox** [comment]
A little late, but I'm here now.

**Pull request merged**
