### PR TITLE
halium: do not reboot on Android 8+ devices when in power off charging mode

### PR DESCRIPTION
**Pull request by NotKit**
This changes cafa7330 to continue boot normally instead of rebooting when device is started in offline charging mode.

Displaying charging animation will be then handled by LXC container inside rootfs.

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This has been tested with no ill effect on the Xperia X running Ubuntu Touch; and tested on the Pixel 3a with required extra change https://gitlab.com/ubports/core/rootfs-builder-debos/-/merge_requests/30, commenting out the reboot for charger mode in [Jumpercable](https://github.com/ubports/jumpercable), and a change to initrc: https://github.com/fredldotme/android_device_google_bonito/commit/cb1da2f72c9b56cd2109f27d684625ce3376fd2e

Given this requires a change to init.rc, I would prefer waiting to merge this until after Ubuntu Touch's OTA-17. That will give porters working on Ubuntu Touch more time to make the required init changes.

Without the init.rc change, the device will probably just sit at the vendor's splash screen indefinitely.

Would also prefer at least an ack from LuneOS and Droidian.

**Comment by Tofee** [comment]
I don't see any issue on our side. However I'm not sure why the LXC container should handle the charging animation ? Why wouldn't that be handled by the distro itself, like all other graphic display ?

**Comment by UniversalSuperBox** [comment]
@Tofee, we also considered implementing the charging animation in the distro's userspace. However, Android's charging binary is already *there* and it's always possible that it does something that actually affects charging, like thermal throttling or enabling fast charge.

In particular, [healthd in charger mode](https://android.googlesource.com/platform/system/core/+/master/healthd/healthd_mode_charger.cpp) has become really advanced. Why reimplement that if we don't have to?

**Comment by Tofee** [comment]
@UniversalSuperBox I agree that it would be a waste of time to implement the same thing twice. Mainly, I am just a bit concerned about conflicts between the wayland compositor, which so far was the only app using the screen, and this android charger animation.

For the actual charging logic, I totally agree we should reuse Android's implementation.

**Comment by NotKit** [comment]
Yes, it will require some logic OS side to prevent starting the compositor if container booted into charging mode (ro.bootmode=charger). Does LuneOS have charging animation implemented with Wayland compositor? Because currently halium-boot always reboots when the device is in charging mode on Android 9 anyway.

**Comment by Tofee** [comment]
@NotKit there is currently no charging animation in LuneOS; I don't remember having seen our devices boot into Android 9 though, it just boots to rootfs, so our initrd must behave slightly differently I guess. I'll have to check that.

**Comment by Verevka** [comment]
I checked on my Xiaomi MI6 (sagit) halium9.0 ubuntu touch, works well.

**Comment by UniversalSuperBox** [comment]
@Tofee, do you see any reason to block this then?

**Comment by Tofee** [comment]
@UniversalSuperBox no that's fine, let's go forward

**Comment by UniversalSuperBox** [comment]
Okay. We haven't heard from Droidian yet, but I believe the project's maintainers have had plenty of time to comment on this now.

**Review by UniversalSuperBox — APPROVED** [review]
CI failure is largely not a concern, and this tests out fine on halium7 and halium9.

**Pull request merged**
