### PR TITLE
Add support for devices with dynamic partitions

### PR DESCRIPTION
**Pull request by amartinz**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
I'm not sure if we should do this. One of the original design goals of initramfs-tools-halium was to move it to using Debian infrastructure instead of UBports. If that was not a concern, we would have been using initramfs-tools-ubuntu-touch this whole time.

The original pitch for initramfs-tools-halium is still open: https://github.com/Halium/projectmanagement/issues/55

In the intervening four years, some things have changed. In particular, Android decided to get rid of initramfs for android9 system-as-root devices. This meant that we were unable to carry initramfs-tools-halium for many devices, so we devised [Jumpercable](https://gitlab.com/ubports/core/hybris-support/jumpercable) and moved a lot of the mounting logic to the rootfs in general. For Ubuntu Touch based on Ubuntu 20.04, we've performed [a small rearchitecture](https://gitlab.com/ubports/core/hybris-support/lxc-android-config/-/merge_requests/52) of our boot and mount logic to actually make the dream of a small initramfs (carried by some ever since we started using initramfs-tools-halium) more possible.

Most importantly: The udev race is no longer a problem. We let Linux mount the system partition (via `root=` on the cmdline) and provide the data partition as a numbered entry (via `datapart=/dev/mmcblk...` on the cmdline). We [mount Android partitions smarter](https://gitlab.com/ubports/core/hybris-support/lxc-android-config/-/blob/ubports/focal/usr/libexec/lxc-android-config/mount-android-partitions) without necessarily requiring udev's coldboot.

I'm not sure if carrying initramfs-tools-halium again into Android 11 is the best choice. In theory, all we need now is an initramfs that knows how to mount the GNU/Linux system's root filesystem and chroot into it. While initramfs-tools-halium may have been a convenient way to build this, I think that a scorched-earth approach will suit better for the future.

Have I mislaid an assumption?

**Comment by amartinz** [comment]
i fully agree with you and to be honest, i took the comfortable approach and reuse existing work done by others.

if possible we should surely rethink that whole topic and slim it down.

that would also mean that we need to find a common ground for focal, because i personally would like if we can drop as much legacy as possible, while others want to carry devices dating back to Android 5.1 to focal.

the sooner we figure out which approach we want to take, the better.

**Comment by UniversalSuperBox** [comment]
The nice thing is that focal doesn't need everything to agree. The code is happy to have all of the mounts set up for it or not. initramfs-tools-halium will live out in Ubuntu Touch for 7.1 and 9.0 (system-as-system) devices at least, and 5.1 if needed. 9.0 system-as-root and beyond only need to make sure that the Ubuntu Touch rootfs is mounted at `/`, that the `datapart` is specified on the command line, and run Jumpercable.

**Comment by UniversalSuperBox** [comment]
Oh, we'll need to add support for dynparts into the system as well. But given the binaries are already around it should be doable.

**Pull request closed without merging**
